hmcts/am-shared-infrastructure

providers.tf

Build error fix
```
[ ] Yes
[X] No
```

Added nprovider version

---

demo.tfvars

https://tools.hmcts.net/jira/browse/AM-833
```
[ ] Yes
[X] No
```

Add demo.tfvars file

---

key-vault.tf
providers.tf

https://tools.hmcts.net/jira/browse/AM-912
```
[ ] Yes
[X] No
```

Adding AppInsightsInstrumentationKey secret

---

asp.tf

https://tools.hmcts.net/jira/browse/AM-912
```
[ ] Yes
[X] No
```

Removing ap service plan

---

appinsights.tf
key-vault.tf
main.tf

AM-1004
```
[ ] Yes
[X] No
```

Removed interpolation

---

aat.tfvars
ithc.tfvars
key-vault.tf
perftest.tfvars
sandbox.tfvars
variables.tf

https://tools.hmcts.net/jira/browse/AM-1004
```
[ ] Yes
[X] No
```

Remove MI referene - Demo

---

aat.tfvars
demo.tfvars
ithc.tfvars
key-vault.tf
perftest.tfvars
sandbox.tfvars
variables.tf

https://tools.hmcts.net/jira/browse/AM-1004
```
[ ] Yes
[X] No
```

Remove MI referene - Perftest

---

.gitignore
aat.tfvars
demo.tfvars
ithc.tfvars
key-vault.tf
perftest.tfvars
sandbox.tfvars
variables.tf

https://tools.hmcts.net/jira/browse/AM-1004
```
[ ] Yes
[X] No
```

Remove MI referene - SandBox

---

demo.tfvars

https://tools.hmcts.net/jira/browse/AM-1004
```
[ ] Yes
[X] No
```

Remove MI reference from demo.tfvars

---

key-vault.tf

https://tools.hmcts.net/jira/browse/AM-1104
```
[ ] Yes
[X] No
```

Update module ref - Demo

---

key-vault.tf

https://tools.hmcts.net/jira/browse/AM-1104
```
[ ] Yes
[X] No
```

Update module ref: PerfTest

---

key-vault.tf

https://tools.hmcts.net/jira/browse/AM-1104
```
[ ] Yes
[X] No
```

Update module ref - Master

---

Jenkinsfile_CNP
appinsights.tf
key-vault.tf

https://tools.hmcts.net/jira/browse/AM-1137
Testing pipeline changes
```
[ ] Yes
[X] No
```

Add branc sync script

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/AM-1137
```
[ ] Yes
[X] No
```

Remove test ref

---

key-vault.tf

NA
Create secret to store RD caseworker topic shared access key
```
[ ] Yes
[X] No
```

Add rd caseworker topic key

---

key-vault.tf

https://tools.hmcts.net/jira/browse/AM-1270
```
[ ] Yes
[X] No
```

Add primary shared access key for judicial topic

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/AM-1270
```
[ ] Yes
[X] No
```

Add ithc to sync branches

---

key-vault.tf
main.tf
send-grid.tf
terraform.tf
variables.tf

https://tools.hmcts.net/jira/browse/AM-1521
Add sendgrid secrets
```
[ ] Yes
[X] No
```

Add sendgrid secrets

---

README.md
output.tf

NA
Remove unwanted output and update readme file.
```
[ ] Yes
[X] No
```

Remove unwanted output

---

terraform.tf

NA
Add azuread provider to fix build issues
```
[ ] Yes
[X] No
```

Add azuread provider to fix build issues

---

aat.tfvars

https://tools.hmcts.net/jira/browse/DTSAM-93
Add fpl to additional_managed_identities_access in Preview

DTSAM-93 Add fpl to additional_managed_identities_access in Preview

---

appinsights.tf
main.tf
terraform.tf
variables.tf

https://tools.hmcts.net/jira/browse/CME-257
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change

CME-257: Update azurerm

---

aat.tfvars

[DTSAM-842](https://tools.hmcts.net/jira/browse/DTSAM-842) _"Grant PCS access to the AM AAT Key Vault, for usage with Preview"_
Grant PCS access to the AM AAT Key Vault, for usage with Preview.

DTSAM-842 Grant PCS access to the AM AAT Key Vault

---

aat.tfvars

[DTSAM-864](https://tools.hmcts.net/jira/browse/DTSAM-864) _"Grant Enforcement access to the AM AAT Key Vault, for usage with Preview"_
Grant  enforcement access to the AM AAT Key Vault, for usage with Preview.

DTSAM-864 Grant Enforcement access to the AM AAT Key Vault

---

aat.tfvars

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?

Add HMC for Preview access
